# Global rules
arrowParens: always
bracketSpacing: false
endOfLine: lf
printWidth: 80
proseWrap: always
quoteProps: consistent
singleQuote: true
tabWidth: 4
trailingComma: all

# Overrides
overrides:
  - files: '*.{json,md,proto,yml}'
    options:
      tabWidth: 2
